import Head from 'next/head'
import Image from 'next/image'
import Details from '../components/Details'
import Products from '../components/Products'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import CartDropdown from '../components/CartDropdown'

export default function Home() {
  return (
    <div className="main-container">
      <Head>
        <title>Bejamas App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <header>
          <Navbar/>
        </header>
        <CartDropdown/>
        <Details/>
        <Products/>
      </main>

    
    </div>
  )
}
